// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace PSTableViewExample.iOS
{
	public partial class HeaderCell : BaseCell
	{
		public const string Key = "HeaderCell";

		public HeaderCell (IntPtr handle) : base (handle)
		{
		}
			
		public override void ConfigureSubviews (IListItemViewModel baseViewModel)
		{
			var viewModel = baseViewModel as HeaderViewModel;

			TitleLabel.Text = viewModel.Text;
		}
	}
}
